# Generated by Django 6.1 on 2026-08-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='token_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
